apiVersion: v2
description: A Helm chart for Mastodon
name: mastodon
sources:
- https://github.com/timwalls/mastodon-chart
- https://github.com/tootsuite/mastodon
maintainers:
- email: dt@dave-vlab.com
  name: davidthamwf
version: 4.0.2
appVersion: 4.0.2
engine: gotpl
